#!/usr/bin/python
# Copyright (C) 2009-2010 by Jason Ansel
# jansel@csail.mit.edu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import re
from os.path import dirname, join

#sqlite3 show database file (will be created)
showdb_file="~/.showdb"

#text file listing subscribed shows (regexp)
filters_file=join(dirname(__file__), "filters.list")

#directory to place downloads
download_dir="~/tv"

#configuration for rssshowfeed
rss_feed_urls = ["http://www.ezrss.it/feed/", "http://rss.bt-chat.com/?cat=9"]
#rss_feed_urls = ["http://www.ezrss.it/feed/"]
rss_interval=3600
rss_timeout=60

#configuration for ircshowfeed
irc_servers=['irc.shoutcast.com', 'irc.umich.edu', 'irc.paraphysics.net', 'efnet.multiplay.co.uk', 'irc.igs.ca', 'irc.blessed.net', 'irc.prison.net']
irc_channels=["#eztv", "#bt-chat"]
#irc_channels=["#eztv"]

#configuration for monitorfeeds
check_interval=3600
check_delay=60

#name chosen randomly from this list (generated by pwgen)
irc_names=['asheeghouj', 'aethohgain', 'ooweishedu', 'cheeshusho', 'ahngengoit', 'oocaisheok', 'ohkeethaem', 'jochaceaju', 'kucuocooju', 'shaetheika', 'owahghasoa', 'oopaxeephi', 'easaepaipe', 'ahzaixueko', 'iefefoongo', 'caephophau', 'aesheeghaj', 'xiengeolep', 'riedaepoop', 'yaiquahdee', 'uuvahsohzo', 'aitheeshof', 'zedeithohd', 'aiseemaesh', 'ooxohchaid', 'aiheixoshe', 'ohyiepahmi', 'ooghaequae', 'ohoalohyee', 'aikeingaik', 'uvuaciepho', 'ifeishaihu', 'oogoobahla', 'piemowieph', 'iehiewooth', 'ohseimothe', 'shaewuajao', 'aophahphie', 'veedungeiv', 'heiwahlaed', 'daigoringo', 'fuceingici', 'iuphaepoom', 'oovuufohli', 'shamodahvi', 'ohthaeloul', 'teiphaelue', 'ceixahvoht', 'equiephouc', 'ieniasairo', 'yiesoefije', 'quaicohphi', 'mailaengoh', 'aiwaeghoog', 'dusanieril', 'quieduayei', 'eeweezaesh', 'reghuchied', 'dauceizeeh', 'ahlookaice', 'pohcoxukev', 'thahghohqu', 'teyajahphi', 'timeingose']

DEBUG=False

#macro to build a list of compiled regular expressions (helper below)
relist = lambda *rxl: map(lambda rx: re.compile(rx, re.IGNORECASE), rxl)

#split a show string into showname, season, episode
titlere_SE = relist(
    r"^(.*) [-].*[. _]S([0-9]+)[. _]?E([0-9]+)",
    r"^(.*)[. _]S([0-9]+)[. _]?E([0-9]+)",
    r"^(.*)[. _]Season[. ]([0-9]+)[. _]?Episode[. ]([0-9]+)",
    r"^(.*)[. _\[]S?([0-9]+)xE?([0-9]+)",
    r"^(.*)[. _]([0-9]+)of([0-9]+)",
    r"^(.*)[. _](20[0-9][0-9])[. _]E([0-9]+)"
)

#split a show string into showname, datestring
titlere_DATE = relist(
  r"^(.*)[. _](20[0-9][0-9][. -][0-9]+[. -][0-9]+)", 
  r"^(.*)[. _]([a-z]+[. _][0-9]+[,]?[. _]20[0-9][0-9])" 
)

#filter usernames in IRC channels who might announce shows
irc_usernameFilters = relist(
  r"bot"
)

#filter messages that might be announcing shows, into showstring, url
irc_msgFilters = relist(
  r"Out now: (.*) - (http[:].*)", 
  r"\[[0-9]+\] (.*) - (http[:].*)", 
  r"\[New Torrent - #[0-9]+\] \(.* - TV\) (.*) - (http[:].*)"
)

#msgs to ignore and not put in logs
irc_msgFiltersIgnore = relist(
  r"Latest Releases", 
  r"EZTV is looking for more seeders", 
  r"Hey guys please keep your torrents open", 
  r"Help us to keep EZTV alive",
  r"[#]eztv is a spoiler-free zone.*",
  r"[^ ]+, Try [!]latest or http[:][/][/]eztv[.]it"
)

